Repository uoftblueprint/tces, pull requests merged in 2023-11, with the labels that each got.

#21 TCES-41 urd create and update user information to be updated
  client/src/App.jsx
  client/src/components/create-user-component/create-user-component.jsx
  client/src/components/create-user-component/index.styles.jsx
  client/src/components/edit-user-component/edit-user-component.jsx
  client/src/components/edit-user-component/index.styles.jsx
  client/src/pages/create-user/create-user.jsx
  client/src/pages/edit-user/edit-user.jsx
Labels: Frontend, Design Approved 🎨

#28 Jordanjanakievski/add code coverage for testing
  server/package-lock.json
  server/package.json
  server/src/middlewares/auth/isAdmin.js
  server/src/middlewares/auth/isLoggedIn.js
  server/var/db/sessions.db
Labels: Backend

#31 TCES-30 urd import clients and employers
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/import-component/index.jsx
  client/src/components/import-component/index.styles.jsx
  client/src/pages/import/index.jsx
Labels: Design Approved 🎨
