Repository uoftblueprint/tces, pull requests merged in 2024-05, with the labels that each got.

#68 TCES-70 Add pages hotfix option to remove multiple of the same
  client/package-lock.json
  client/src/components/add-employer-component/company-info-component/index.jsx
  client/src/components/add-employer-component/employer-contact-component/index.jsx
  client/src/components/add-employer-component/employer-job-lead-component/index.jsx
  client/src/components/add-job-lead-component/index.jsx
  client/src/components/add-job-lead-component/jobLeadCard.jsx
  client/src/components/create-client-component/ClientCard.jsx
  client/src/components/create-client-component/create-client-component.jsx
Labels: Frontend, feature

#61 Jordanjanakievski/tces 62 cln fix phone number masking
  client/src/components/add-employer-component/company-info-component/index.jsx
  client/src/components/add-employer-component/employer-contact-component/index.jsx
  client/src/components/client-dashboard-component/client-dashboard-filter/FilterCard.jsx
  client/src/components/client-page/client-timeline/client-timeline-entries/index.jsx
  client/src/components/client-page/index.jsx
  client/src/components/create-client-component/ClientCard.jsx
  client/src/components/dashboard-component/index.styles.jsx
  client/src/components/edit-job-lead-component/edit-job-lead-form/index.jsx
  client/src/components/employer-component/box-row-component/index.jsx
  client/src/components/employer-component/contacts-information-card/index.jsx
  client/src/components/employer-component/employer-information-card/index.jsx
  client/src/components/employer-dashboard-component/employer-dashboard-filter/index.jsx
  client/src/components/employer-dashboard-component/index.styles.jsx
  client/src/components/job-lead-dashboard-component/job-lead-dashboard-filters/index.jsx
  client/src/components/timeline-entry-components/employer-entry-component/index.jsx
  client/src/components/timeline-window-component/empWindow.jsx
  server/src/controllers/client/getAllClients.js
  server/src/controllers/client_timeline_entries/getAllClientTimelineEntries.js
  server/src/controllers/employer/getAllEmployers.js
  server/src/controllers/employer/updateEmployer.js
Labels: Ready for Review

#80 Jordanjanakievski/tces 71 restrict employers shown when adding a job lead after a
  client/src/App.jsx
  client/src/components/add-job-lead-component/addJobLead.jsx
  client/src/components/add-job-lead-component/index.jsx
  client/src/components/add-job-lead-component/jobLeadCard.jsx
  client/src/pages/add-job-lead/index.jsx
Labels: Frontend

#79 Jordanjanakievski/tces 69 add the ability to filter by employer contact name andor
  client/src/components/employer-dashboard-component/employer-dashboard-filter/index.jsx
  client/src/components/employer-dashboard-component/index.jsx
  server/src/controllers/employer/getAllEmployers.js
Labels: Ready for Review

#81 Jordanjanakievski/tces 78 client and job lead linkage frontend
  client/src/components/edit-job-lead-component/edit-job-lead-form/index.jsx
  client/src/components/edit-job-lead-component/edit-job-lead-linkages/index.jsx
  client/src/components/edit-job-lead-component/edit-job-lead-timeline/index.jsx
  client/src/components/edit-job-lead-component/index.jsx
  client/src/components/timeline-create-entry-components/placed-entry-component/index.jsx
  client/src/utils/api.js
  server/src/controllers/client/updateClient.js
Labels: Ready for Review
